services:
  checkout:
    environment:
      OTEL_METRIC_EXPORT_INTERVAL: "2000"
  load-generator:
    environment:
      LOAD_GENERATOR_VUS: "10"
  otel-collector:
    volumes:
      - ${FLOWPULSE_CAPTURE_DIR}:/flowpulse
